"""typo in restaurant model

Revision ID: 1e67e5e87b00
Revises: 2b42073dc8e0
Create Date: 2024-08-05 21:51:09.324254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e67e5e87b00'
down_revision = '2b42073dc8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine_type', sa.String(), nullable=True))
        batch_op.drop_column('cusuine_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cusuine_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('cuisine_type')

    # ### end Alembic commands ###
