"""changed restaurants model

Revision ID: e5264ee821c3
Revises: 1e67e5e87b00
Create Date: 2024-08-06 15:04:27.736009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5264ee821c3'
down_revision = '1e67e5e87b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hours_of_operation', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('menu_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('display_phone', sa.String(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('display_phone')
        batch_op.drop_column('menu_url')
        batch_op.drop_column('hours_of_operation')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
