"""added new columns for user

Revision ID: e74e2b31d486
Revises: dc145e80ef4c
Create Date: 2024-07-30 13:39:58.173985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74e2b31d486'
down_revision = 'dc145e80ef4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('preparation_time', sa.Integer(), nullable=True),
    sa.Column('cooking_time', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intolerance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.String(), nullable=True))
        batch_op.drop_column('restrictions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restrictions', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('cuisine')
        batch_op.drop_column('intolerance')

    op.drop_table('recipes')
    # ### end Alembic commands ###
